import {Injectable} from '@angular/core';

const countries = [
  {
    name: 'Afghanistan',
    dial_code: '+93',
    code: 'AF',
    img: '../../assets/countries/flag-of-Afghanistan.png',
  },
  {
    name: 'Albania',
    dial_code: '+355',
    code: 'AL',
    img: '../../assets/countries/flag-of-Albania.png',
  },
  {
    name: 'Algeria',
    dial_code: '+213',
    code: 'DZ',
    img: '../../assets/countries/flag-of-Algeria',
  },
  {
    name: 'Andorra',
    dial_code: '+376',
    code: 'AD',
    img: '../../assets/countries/flag-of-Andorra',
  },
  {
    name: 'Angola',
    dial_code: '+244',
    code: 'AO',
    img: '../../assets/countries/flag-of-Angola',
  },
  {
    name: 'Antigua',
    dial_code: '+1268',
    code: 'AG'
  },
  {
    name: 'Argentina',
    dial_code: '+54',
    code: 'AR',
    img: '../../assets/countries/flag-of-Antigua',
  },
  {
    name: 'Armenia',
    dial_code: '+374',
    code: 'AM',
    img: '../../assets/countries/flag-of-Armenia',
  },
  {
    name: 'Australia',
    dial_code: '+61',
    code: 'AU',
    img: '../../assets/countries/flag-of-Australia',
  },
  {
    name: 'Austria',
    dial_code: '+43',
    code: 'AT',
    img: '../../assets/countries/flag-of-Austria',
  },
  {
    name: 'Azerbaijan',
    dial_code: '+994',
    code: 'AZ',
    img: '../../assets/countries/flag-of-Azerbaijan',
  },
  {
    name: 'Bahamas',
    dial_code: '+1 242',
    code: 'BS',
    img: '../../assets/countries/flag-of-Bahamas',
  },
  {
    name: 'Bahrain',
    dial_code: '+973',
    code: 'BH',
    img: '../../assets/countries/flag-of-Bahrain',
  },
  {
    name: 'Bangladesh',
    dial_code: '+880',
    code: 'BD',
    img: '../../assets/countries/flag-of-Bangladesh',
  },
  {
    name: 'Barbados',
    dial_code: '+1 246',
    code: 'BB',
    img: '../../assets/countries/flag-of-Barbados',
  },
  {
    name: 'Belarus',
    dial_code: '+375',
    code: 'BY',
    img: '../../assets/countries/flag-of-Belarus',
  },
  {
    name: 'Belgium',
    dial_code: '+32',
    code: 'BE',
    img: '../../assets/countries/flag-of-Belgium',
  },
  {
    name: 'Belize',
    dial_code: '+501',
    code: 'BZ',
    img: '../../assets/countries/flag-of-Belize',
  },
  {
    name: 'Benin',
    dial_code: '+229',
    code: 'BJ',
    img: '../../assets/countries/flag-of-Benin',
  },
  {
    name: 'Bhutan',
    dial_code: '+975',
    code: 'BT',
    img: '../../assets/countries/flag-of-Bhutan',
  },
  {
    name: 'Bolivia',
    dial_code: '+591',
    code: 'BO',
    img: '../../assets/countries/flag-of-Bolivia',
  },
  {
    name: 'Bosnia-Herzegovina',
    dial_code: '+387',
    code: 'BA',
    img: '../../assets/countries/flag-of-Bosnia-Herzegovina',
  },
  {
    name: 'Botswana',
    dial_code: '+267',
    code: 'BW'
  },
  {
    name: 'Brazil',
    dial_code: '+55',
    code: 'BR',
    img: '../../assets/countries/flag-of-Botswana',
  },
  {
    name: 'Brunei',
    dial_code: '+673',
    code: 'BN',
    img: '../../assets/countries/flag-of-Brunei',
  },
  {
    name: 'Bulgaria',
    dial_code: '+359',
    code: 'BG',
    img: '../../assets/countries/flag-of-Bulgaria',
  },
  {
    name: 'Burkina-Faso',
    dial_code: '+226',
    code: 'BF',
    img: '../../assets/countries/flag-of-Burkina-Faso',
  },
  {
    name: 'Burundi',
    dial_code: '+257',
    code: 'BI',
    img: '../../assets/countries/flag-of-Burundi',
  },
  {
    name: 'Cambodia',
    dial_code: '+855',
    code: 'KH',
    img: '../../assets/countries/flag-of-Cambodia',
  },
  {
    name: 'Cameroon',
    dial_code: '+237',
    code: 'CM',
    img: '../../assets/countries/flag-of-Cameroon',
  },
  {
    name: 'Canada',
    dial_code: '+1',
    code: 'CA',
    img: '../../assets/countries/flag-of-Canada',
  },
  {
    name: 'Central-African-Republic',
    dial_code: '+236',
    code: 'CF',
    img: '../../assets/countries/flag-of-Central-African-Republic',
  },
  {
    name: 'Chad',
    dial_code: '+235',
    code: 'TD',
    img: '../../assets/countries/flag-of-Chad',
  },
  {
    name: 'Chile',
    dial_code: '+56',
    code: 'CL',
    img: '../../assets/countries/flag-of-Chile',
  },
  {
    name: 'China',
    dial_code: '+86',
    code: 'CN',
    img: '../../assets/countries/flag-of-China',
  },
  {
    name: 'Colombia',
    dial_code: '+57',
    code: 'CO',
    img: '../../assets/countries/flag-of-Colombia',
  },
  {
    name: 'Comoros',
    dial_code: '+269',
    code: 'KM',
    img: '../../assets/countries/flag-of-Comoros',
  },
  {
    name: 'Congo',
    dial_code: '+242',
    code: 'CG',
    img: '../../assets/countries/flag-of-Congo',
  },
  {
    name: 'Congo-Democratic-Republic-of',
    dial_code: '+243',
    code: 'CD',
    img: '../../assets/countries/flag-of-Congo-Democratic-Republic-of',
  },
  {
    name: 'Costa-Rica',
    dial_code: '+506',
    code: 'CR',
    img: '../../assets/countries/flag-of-Costa-Rica',
  },
  {
    name: 'Cote-d-Ivoire',
    dial_code: '+225',
    code: 'CI',
    img: '../../assets/countries/flag-of-Cote-d-Ivoire',
  },
  {
    name: 'Croatia',
    dial_code: '+385',
    code: 'HR',
    img: '../../assets/countries/flag-of-Croatia',
  },
  {
    name: 'Cuba',
    dial_code: '+53',
    code: 'CU',
    img: '../../assets/countries/flag-of-Cuba',
  },
  {
    name: 'Cyprus',
    dial_code: '+357',
    code: 'CY',
    img: '../../assets/countries/flag-of-Cyprus',
  },
  {
    name: 'Czech-Republic',
    dial_code: '+420',
    code: 'CZ',
    img: '../../assets/countries/flag-of-Czech-Republic',
  },
  {
    name: 'Denmark',
    dial_code: '+45',
    code: 'DK',
    img: '../../assets/countries/flag-of-Denmark',
  },
  {
    name: 'Djibouti',
    dial_code: '+253',
    code: 'DJ',
    img: '../../assets/countries/flag-of-Djibouti',
  },
  {
    name: 'Dominica',
    dial_code: '+1 767',
    code: 'DM',
    img: '../../assets/countries/flag-of-Dominica',
  },
  {
    name: 'Dominican-Republic',
    dial_code: '+1 849',
    code: 'DO',
    img: '../../assets/countries/flag-of-Dominican-Republic',
  },
  {
    name: 'Ecuador',
    dial_code: '+593',
    code: 'EC',
    img: '../../assets/countries/flag-of-Ecuador',
  },
  {
    name: 'Egypt',
    dial_code: '+20',
    code: 'EG',
    img: '../../assets/countries/flag-of-Egypt',
  },
  {
    name: 'El-Salvador',
    dial_code: '+503',
    code: 'SV',
    img: '../../assets/countries/flag-of-El-Salvador',
  },
  {
    name: 'Equatorial-Guinea',
    dial_code: '+240',
    code: 'GQ',
    img: '../../assets/countries/flag-of-Equatorial-Guinea',
  },
  {
    name: 'Eritrea',
    dial_code: '+291',
    code: 'ER',
    img: '../../assets/countries/flag-of-Eritrea',
  },
  {
    name: 'Estonia',
    dial_code: '+372',
    code: 'EE',
    img: '../../assets/countries/flag-of-Estonia',
  },
  {
    name: 'Ethiopia',
    dial_code: '+251',
    code: 'ET',
    img: '../../assets/countries/flag-of-Ethiopia',
  },
  {
    name: 'Fiji',
    dial_code: '+679',
    code: 'FJ',
    img: '../../assets/countries/flag-of-Fiji',
  },
  {
    name: 'Finland',
    dial_code: '+358',
    code: 'FI',
    img: '../../assets/countries/flag-of-Finland',
  },
  {
    name: 'France',
    dial_code: '+33',
    code: 'FR',
    img: '../../assets/countries/flag-of-France',
  },
  {
    name: 'Gabon',
    dial_code: '+241',
    code: 'GA',
    img: '../../assets/countries/flag-of-Gabon',
  },
  {
    name: 'Gambia',
    dial_code: '+220',
    code: 'GM',
    img: '../../assets/countries/flag-of-Gambia',
  },
  {
    name: 'Georgia',
    dial_code: '+995',
    code: 'GE',
    img: '../../assets/countries/flag-of-Georgia',
  },
  {
    name: 'Germany',
    dial_code: '+49',
    code: 'DE',
    img: '../../assets/countries/flag-of-Germany',
  },
  {
    name: 'Ghana',
    dial_code: '+233',
    code: 'GH',
    img: '../../assets/countries/flag-of-Ghana',
  },
  {
    name: 'Greece',
    dial_code: '+30',
    code: 'GR',
    img: '../../assets/countries/flag-of-Greece',
  },
  {
    name: 'Grenada',
    dial_code: '+1 473',
    code: 'GD',
    img: '../../assets/countries/flag-of-Grenada',
  },
  {
    name: 'Guatemala',
    dial_code: '+502',
    code: 'GT',
    img: '../../assets/countries/flag-of-Guatemala',
  },
  {
    name: 'Guinea',
    dial_code: '+224',
    code: 'GN',
    img: '../../assets/countries/flag-of-Guinea',
  },
  {
    name: 'Guinea-Bissau',
    dial_code: '+245',
    code: 'GW',
    img: '../../assets/countries/flag-of-Guinea-Bissau',
  },
  {
    name: 'Guyana',
    dial_code: '+595',
    code: 'GY',
    img: '../../assets/countries/flag-of-Guyana',
  },
  {
    name: 'Haiti',
    dial_code: '+509',
    code: 'HT',
    img: '../../assets/countries/flag-of-Haiti',
  },
  {
    name: 'Honduras',
    dial_code: '+504',
    code: 'HN',
    img: '../../assets/countries/flag-of-Honduras',
  },
  {
    name: 'Hungary',
    dial_code: '+36',
    code: 'HU',
    img: '../../assets/countries/flag-of-Hungary',
  },
  {
    name: 'Iceland',
    dial_code: '+354',
    code: 'IS',
    img: '../../assets/countries/flag-of-Iceland',
  },
  {
    name: 'India',
    dial_code: '+91',
    code: 'IN',
    img: '../../assets/countries/flag-of-India',
  },
  {
    name: 'Indonesia',
    dial_code: '+62',
    code: 'ID',
    img: '../../assets/countries/flag-of-Indonesia',
  },
  {
    name: 'Iran',
    dial_code: '+98',
    code: 'IR',
    img: '../../assets/countries/flag-of-Iran',
  },
  {
    name: 'Iraq',
    dial_code: '+964',
    code: 'IQ',
    img: '../../assets/countries/flag-of-Iraq',
  },
  {
    name: 'Ireland',
    dial_code: '+353',
    code: 'IE',
    img: '../../assets/countries/flag-of-Ireland',
  },
  {
    name: 'Israel',
    dial_code: '+972',
    code: 'IL',
    img: '../../assets/countries/flag-of-Israel',
  },
  {
    name: 'Italy',
    dial_code: '+39',
    code: 'IT',
    img: '../../assets/countries/flag-of-Italy',
  },
  {
    name: 'Jamaica',
    dial_code: '+1 876',
    code: 'JM',
    img: '../../assets/countries/flag-of-Jamaica',
  },
  {
    name: 'Japan',
    dial_code: '+81',
    code: 'JP',
    img: '../../assets/countries/flag-of-Japan',
  },
  {
    name: 'Jordan',
    dial_code: '+962',
    code: 'JO',
    img: '../../assets/countries/flag-of-Jordan',
  },
  {
    name: 'Kazakhstan',
    dial_code: '+7 7',
    code: 'KZ',
    img: '../../assets/countries/flag-of-Kazakhstan',
  },
  {
    name: 'Kenya',
    dial_code: '+254',
    code: 'KE',
    img: '../../assets/countries/flag-of-Kenya',
  },
  {
    name: 'Kiribati',
    dial_code: '+686',
    code: 'KI',
    img: '../../assets/countries/flag-of-Kiribati',
  },
  {
    name: 'Korea-North',
    dial_code: '+850',
    code: 'KP',
    img: '../../assets/countries/flag-of-Korea-North',
  },
  {
    name: 'Korea-South',
    dial_code: '+82',
    code: 'KR',
    img: '../../assets/countries/flag-of-Korea-South',
  },
  {
    name: 'Kuwait',
    dial_code: '+965',
    code: 'KW',
    img: '../../assets/countries/flag-of-Kuwait',
  },
  {
    name: 'Kyrgyzstan',
    dial_code: '+996',
    code: 'KG',
    img: '../../assets/countries/flag-of-Kyrgyzstan',
  },
  {
    name: 'Laos',
    dial_code: '+856',
    code: 'LA',
    img: '../../assets/countries/flag-of-Laos',
  },
  {
    name: 'Latvia',
    dial_code: '+371',
    code: 'LV',
    img: '../../assets/countries/flag-of-Latvia',
  },
  {
    name: 'Lebanon',
    dial_code: '+961',
    code: 'LB',
    img: '../../assets/countries/flag-of-Lebanon',
  },
  {
    name: 'Lesotho',
    dial_code: '+266',
    code: 'LS',
    img: '../../assets/countries/flag-of-Lesotho',
  },
  {
    name: 'Liberia',
    dial_code: '+231',
    code: 'LR',
    img: '../../assets/countries/flag-of-Liberia',
  },
  {
    name: 'Libya',
    dial_code: '+218',
    code: 'LY',
    img: '../../assets/countries/flag-of-Libya',
  },
  {
    name: 'Liechtenstein',
    dial_code: '+423',
    code: 'LI',
    img: '../../assets/countries/flag-of-Liechtenstein',
  },
  {
    name: 'Lithuania',
    dial_code: '+370',
    code: 'LT',
    img: '../../assets/countries/flag-of-Lithuania',
  },
  {
    name: 'Luxembourg',
    dial_code: '+352',
    code: 'LU',
    img: '../../assets/countries/flag-of-Luxembourg',
  },
  {
    name: 'Madagascar',
    dial_code: '+261',
    code: 'MG',
    img: '../../assets/countries/flag-of-Madagascar',
  },
  {
    name: 'Malawi',
    dial_code: '+265',
    code: 'MW',
    img: '../../assets/countries/flag-of-Malawi',
  },
  {
    name: 'Malaysia',
    dial_code: '+60',
    code: 'MY',
    img: '../../assets/countries/flag-of-Malaysia',
  },
  {
    name: 'Maldives',
    dial_code: '+960',
    code: 'MV',
    img: '../../assets/countries/flag-of-Maldives',
  },
  {
    name: 'Mali',
    dial_code: '+223',
    code: 'ML',
    img: '../../assets/countries/flag-of-Mali',
  },
  {
    name: 'Malta',
    dial_code: '+356',
    code: 'MT',
    img: '../../assets/countries/flag-of-Malta',
  },
  {
    name: 'Marshall-Islands',
    dial_code: '+692',
    code: 'MH',
    img: '../../assets/countries/flag-of-Marshall-Islands',
  },
  {
    name: 'Mauritania',
    dial_code: '+222',
    code: 'MR',
    img: '../../assets/countries/flag-of-Mauritania',
  },
  {
    name: 'Mauritius',
    dial_code: '+230',
    code: 'MU',
    img: '../../assets/countries/flag-of-Mauritius',
  },
  {
    name: 'Mexico',
    dial_code: '+52',
    code: 'MX',
    img: '../../assets/countries/flag-of-Mexico',
  },
  {
    name: 'Micronesia',
    dial_code: '+691',
    code: 'FM',
    img: '../../assets/countries/flag-of-Micronesia',
  },
  {
    name: 'Moldova',
    dial_code: '+373',
    code: 'MD',
    img: '../../assets/countries/flag-of-Moldova',
  },
  {
    name: 'Monaco',
    dial_code: '+377',
    code: 'MC',
    img: '../../assets/countries/flag-of-Monaco',
  },
  {
    name: 'Mongolia',
    dial_code: '+976',
    code: 'MN',
    img: '../../assets/countries/flag-of-Mongolia',
  },
  {
    name: 'Montenegro',
    dial_code: '+382',
    code: 'ME',
    img: '../../assets/countries/flag-of-Montenegro',
  },
  {
    name: 'Morocco',
    dial_code: '+212',
    code: 'MA',
    img: '../../assets/countries/flag-of-Morocco',
  },
  {
    name: 'Mozambique',
    dial_code: '+258',
    code: 'MZ',
    img: '../../assets/countries/flag-of-Mozambique',
  },
  {
    name: 'Myanmar',
    dial_code: '+95',
    code: 'MM',
    img: '../../assets/countries/flag-of-Myanmar',
  },
  {
    name: 'Namibia',
    dial_code: '+264',
    code: 'NA',
    img: '../../assets/countries/flag-of-Namibia',
  },
  {
    name: 'Nauru',
    dial_code: '+674',
    code: 'NR',
    img: '../../assets/countries/flag-of-Nauru',
  },
  {
    name: 'Nepal',
    dial_code: '+977',
    code: 'NP',
    img: '../../assets/countries/flag-of-Nepal',
  },
  {
    name: 'Netherlands',
    dial_code: '+31',
    code: 'NL',
    img: '../../assets/countries/flag-of-Netherlands',
  },
  {
    name: 'New-Zealand',
    dial_code: '+64',
    code: 'NZ',
    img: '../../assets/countries/flag-of-New-Zealand',
  },
  {
    name: 'Nicaragua',
    dial_code: '+505',
    code: 'NI',
    img: '../../assets/countries/flag-of-Nicaragua',
  },
  {
    name: 'Niger',
    dial_code: '+227',
    code: 'NE',
    img: '../../assets/countries/flag-of-Niger',
  },
  {
    name: 'Nigeria',
    dial_code: '+234',
    code: 'NG',
    img: '../../assets/countries/flag-of-Nigeria',
  },
  {
    name: 'Norway',
    dial_code: '+47',
    code: 'NO',
    img: '../../assets/countries/flag-of-Norway',
  },
  {
    name: 'Oman',
    dial_code: '+968',
    code: 'OM',
    img: '../../assets/countries/flag-of-Oman',
  },
  {
    name: 'Pakistan',
    dial_code: '+92',
    code: 'PK',
    img: '../../assets/countries/flag-of-Pakistan',
  },
  {
    name: 'Palau',
    dial_code: '+680',
    code: 'PW',
    img: '../../assets/countries/flag-of-Palau',
  },
  {
    name: 'Palestine',
    dial_code: '+970',
    code: 'PS',
    img: '../../assets/countries/flag-of-Palestine',
  },
  {
    name: 'Panama',
    dial_code: '+507',
    code: 'PA',
    img: '../../assets/countries/flag-of-Panama',
  },
  {
    name: 'Papua-New-Guinea',
    dial_code: '+675',
    code: 'PG',
    img: '../../assets/countries/flag-of-Papua-New-Guinea',
  },
  {
    name: 'Paraguay',
    dial_code: '+595',
    code: 'PY',
    img: '../../assets/countries/flag-of-Paraguay',
  },
  {
    name: 'Peru',
    dial_code: '+51',
    code: 'PE',
    img: '../../assets/countries/flag-of-Peru',
  },
  {
    name: 'Philippines',
    dial_code: '+63',
    code: 'PH',
    img: '../../assets/countries/flag-of-Philippines',
  },
  {
    name: 'Poland',
    dial_code: '+48',
    code: 'PL',
    img: '../../assets/countries/flag-of-Poland',
  },
  {
    name: 'Portugal',
    dial_code: '+351',
    code: 'PT',
    img: '../../assets/countries/flag-of-Portugal',
  },
  {
    name: 'Qatar',
    dial_code: '+974',
    code: 'QA',
    img: '../../assets/countries/flag-of-Qatar',
  },
  {
    name: 'Romania',
    dial_code: '+40',
    code: 'RO',
    img: '../../assets/countries/flag-of-Romania',
  },
  {
    name: 'Russia',
    dial_code: '+7',
    code: 'RU',
    img: '../../assets/countries/flag-of-Russia',
  },
  {
    name: 'Rwanda',
    dial_code: '+250',
    code: 'RW',
    img: '../../assets/countries/flag-of-Rwanda',
  },
  {
    name: 'Samoa',
    dial_code: '+685',
    code: 'WS',
    img: '../../assets/countries/flag-of-Samoa',
  },
  {
    name: 'San-Marino',
    dial_code: '+378',
    code: 'SM',
    img: '../../assets/countries/flag-of-San-Marino',
  },
  {
    name: 'Sao-Tome-and-Principe',
    dial_code: '+239',
    code: 'ST',
    img: '../../assets/countries/flag-of-Sao-Tome-and-Principe',
  },
  {
    name: 'Saudi-Arabia',
    dial_code: '+966',
    code: 'SA',
    img: '../../assets/countries/flag-of-Saudi-Arabia',
  },
  {
    name: 'Senegal',
    dial_code: '+221',
    code: 'SN',
    img: '../../assets/countries/flag-of-Senegal',
  },
  {
    name: 'Serbia',
    dial_code: '+381',
    code: 'RS',
    img: '../../assets/countries/flag-of-Serbia',
  },
  {
    name: 'Seychelles',
    dial_code: '+248',
    code: 'SC',
    img: '../../assets/countries/flag-of-Seychelles',
  },
  {
    name: 'Sierra-Leone',
    dial_code: '+232',
    code: 'SL',
    img: '../../assets/countries/flag-of-Sierra-Leone',
  },
  {
    name: 'Singapore',
    dial_code: '+65',
    code: 'SG',
    img: '../../assets/countries/flag-of-Singapore',
  },
  {
    name: 'Slovakia',
    dial_code: '+421',
    code: 'SK',
    img: '../../assets/countries/flag-of-Slovakia',
  },
  {
    name: 'Slovenia',
    dial_code: '+386',
    code: 'SI',
    img: '../../assets/countries/flag-of-Slovenia',
  },
  {
    name: 'Solomon-Islands',
    dial_code: '+677',
    code: 'SB',
    img: '../../assets/countries/flag-of-Solomon-Islands',
  },
  {
    name: 'Somalia',
    dial_code: '+252',
    code: 'SO',
    img: '../../assets/countries/flag-of-Somalia',
  },
  {
    name: 'South-Africa',
    dial_code: '+27',
    code: 'ZA',
    img: '../../assets/countries/flag-of-South-Africa',
  },
  {
    name: 'Spain',
    dial_code: '+34',
    code: 'ES',
    img: '../../assets/countries/flag-of-Spain',
  },
  {
    name: 'Sri-Lanka',
    dial_code: '+94',
    code: 'LK',
    img: '../../assets/countries/flag-of-Sri-Lanka',
  },
  {
    name: 'Sudan',
    dial_code: '+249',
    code: 'SD',
    img: '../../assets/countries/flag-of-Sudan',
  },
  {
    name: 'Suriname',
    dial_code: '+597',
    code: 'SR',
    img: '../../assets/countries/flag-of-Suriname',
  },
  {
    name: 'Sweden',
    dial_code: '+46',
    code: 'SE',
    img: '../../assets/countries/flag-of-Sweden',
  },
  {
    name: 'Switzerland',
    dial_code: '+41',
    code: 'CH',
    img: '../../assets/countries/flag-of-Switzerland',
  },
  {
    name: 'Syria',
    dial_code: '+963',
    code: 'SY',
    img: '../../assets/countries/flag-of-Syria',
  },
  {
    name: 'Tajikistan',
    dial_code: '+992',
    code: 'TJ',
    img: '../../assets/countries/flag-of-Tajikistan',
  },
  {
    name: 'Tanzania',
    dial_code: '+255',
    code: 'TZ',
    img: '../../assets/countries/flag-of-Tanzania',
  },
  {
    name: 'Thailand',
    dial_code: '+66',
    code: 'TH',
    img: '../../assets/countries/flag-of-Thailand',
  },
  {
    name: 'Timor-Leste',
    dial_code: '+670',
    code: 'TL',
    img: '../../assets/countries/flag-of-Timor-Leste',
  },
  {
    name: 'Togo',
    dial_code: '+228',
    code: 'TG',
    img: '../../assets/countries/flag-of-Togo',
  },
  {
    name: 'Tonga',
    dial_code: '+676',
    code: 'TO',
    img: '../../assets/countries/flag-of-Tonga',
  },
  {
    name: 'Trinidad-and-Tobago',
    dial_code: '+1 868',
    code: 'TT',
    img: '../../assets/countries/flag-of-Trinidad-and-Tobago',
  },
  {
    name: 'Tunisia',
    dial_code: '+216',
    code: 'TN',
    img: '../../assets/countries/flag-of-Tunisia',
  },
  {
    name: 'Turkey',
    dial_code: '+90',
    code: 'TR',
    img: '../../assets/countries/flag-of-Turkey',
  },
  {
    name: 'Turkmenistan',
    dial_code: '+993',
    code: 'TM',
    img: '../../assets/countries/flag-of-Turkmenistan',
  },
  {
    name: 'Tuvalu',
    dial_code: '+688',
    code: 'TV',
    img: '../../assets/countries/flag-of-Tuvalu',
  },
  {
    name: 'Uganda',
    dial_code: '+256',
    code: 'UG',
    img: '../../assets/countries/flag-of-Uganda',
  },
  {
    name: 'Ukraine',
    dial_code: '+380',
    code: 'UA',
    img: '../../assets/countries/flag-of-Ukraine',
  },
  {
    name: 'United-Arab-Emirates',
    dial_code: '+971',
    code: 'AE',
    img: '../../assets/countries/flag-of-United-Arab-Emirates',
  },
  {
    name: 'United-Kingdom',
    dial_code: '+44',
    code: 'GB',
    img: '../../assets/countries/flag-of-United-Kingdom',
  },
  {
    name: 'United-States-of-America',
    dial_code: '+1',
    code: 'US',
    img: '../../assets/countries/flag-of-United-States-of-America',
  },
  {
    name: 'Uruguay',
    dial_code: '+598',
    code: 'UY',
    img: '../../assets/countries/flag-of-Uruguay',
  },
  {
    name: 'Uzbekistan',
    dial_code: '+998',
    code: 'UZ',
    img: '../../assets/countries/flag-of-Uzbekistan',
  },
  {
    name: 'Vanuatu',
    dial_code: '+678',
    code: 'VU',
    img: '../../assets/countries/flag-of-Vanuatu',
  },
  {
    name: 'Venezuela',
    dial_code: '+58',
    code: 'VE',
    img: '../../assets/countries/flag-of-Venezuela',
  },
  {
    name: 'Vietnam',
    dial_code: '+84',
    code: 'VN',
    img: '../../assets/countries/flag-of-Vietnam',
  },
  {
    name: 'Yemen',
    dial_code: '+967',
    code: 'YE',
    img: '../../assets/countries/flag-of-Yemen',
  },
  {
    name: 'Zambia',
    dial_code: '+260',
    code: 'ZM',
    img: '../../assets/countries/flag-of-Zambia',
  },
  {
    name: 'Zimbabwe',
    dial_code: '+263',
    code: 'ZW',
    img: '../../assets/countries/flag-of-Zimbabwe',
  }
];
@Injectable()
export class CountriesService {

  constructor() {
  }

  getAllCountries() {
    return countries;
  }

  getCountriesByConfig(countriesConfig) {
    return countries.filter((_) => countriesConfig.includes(_.name));
  }
}
